import { describe, expect, it } from 'vitest'
import { AVATARS, AVATAR_GROUPS, defaultAvatarFor, photoUrl } from './avatars'

/*
 * The committed artwork itself, read through Vite rather than the filesystem.
 * This is a browser project with no Node types, and adding them so a test can
 * call readdirSync would also let application code import fs by accident.
 */
const ART = import.meta.glob('../assets/avatars/*.svg', {
  eager: true, query: '?raw', import: 'default',
}) as Record<string, string>

const artFiles = Object.keys(ART).map((path) => path.split('/').pop() as string)

describe('the avatar set', () => {
  it('offers every key it advertises, and has artwork for every key it offers', () => {
    const offered = AVATAR_GROUPS.flatMap((g) => g.keys)
    for (const key of offered) {
      expect(AVATARS[key], `${key} is offered in the picker but has no artwork`).toBeDefined()
    }
    expect(new Set(offered).size).toBe(offered.length)
    // Anything with artwork but never offered is dead weight in the bundle.
    expect(Object.keys(AVATARS).sort()).toEqual([...offered].sort())
  })

  it('has a committed file for every key', () => {
    // The pictures are generated by scripts/build-avatars.mjs and committed.
    // A key whose file never got written imports as undefined and silently
    // falls back to an initial, which looks like a bug in the picker.
    expect(artFiles.sort()).toEqual(Object.keys(AVATARS).map((k) => `${k}.svg`).sort())
  })

  it('draws a different person for every key', () => {
    // The point of offering a choice is that people can find one that looks
    // something like them, so two keys rendering the same figure would make
    // the picker a lie. Compares the artwork, not the filename.
    const drawings = Object.values(ART)
    expect(drawings).toHaveLength(Object.keys(AVATARS).length)
    expect(new Set(drawings).size).toBe(drawings.length)
  })

  it('keeps the keys that are already stored on profiles', () => {
    // These are saved against people. Renaming one does not migrate anything —
    // it silently blanks that person's avatar back to an initial.
    expect(Object.keys(AVATARS).sort()).toEqual(
      ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'm1', 'm2', 'm3', 'm4', 'm5', 'm6'],
    )
  })
})

describe('defaultAvatarFor', () => {
  it('answers for the gender the profile actually stores', () => {
    for (const male of ['male', 'Male', 'M', 'man']) {
      expect(defaultAvatarFor(male)?.startsWith('m')).toBe(true)
    }
    for (const female of ['female', 'Female', 'F', 'woman']) {
      expect(defaultAvatarFor(female)?.startsWith('f')).toBe(true)
    }
  })

  it('declines to guess when it does not know', () => {
    // An initial belongs to nobody in particular, which is the point:
    // picking a face for someone who did not say is worse than a letter.
    for (const unknown of [null, undefined, '', '   ', 'other', 'non-binary', 'prefer not to say']) {
      expect(defaultAvatarFor(unknown)).toBeNull()
    }
  })
})

describe('photoUrl', () => {
  it('puts a stored path under /storage where the server serves it', () => {
    expect(photoUrl('profile-photos/abc.jpg')).toBe('/storage/profile-photos/abc.jpg')
    expect(photoUrl('/profile-photos/abc.jpg')).toBe('/storage/profile-photos/abc.jpg')
  })

  it('leaves an absolute URL alone, so a move to a CDN needs no change here', () => {
    expect(photoUrl('https://cdn.example/a.jpg')).toBe('https://cdn.example/a.jpg')
    expect(photoUrl('http://cdn.example/a.jpg')).toBe('http://cdn.example/a.jpg')
  })
})
